// Shared CSRF verification.
//
// Tokens are generated by @fastify/csrf-protection's reply.generateCsrf(), which
// stores a per-session secret in req.session._csrf and returns tokens.create(secret).
// @fastify/csrf tokens are stateless: any Tokens instance with the same options can
// verify a token against its secret. We keep one instance here and use it for ALL
// verification — both form-encoded routes (token in req.body) and multipart routes
// (token extracted manually after parsing), which is necessary because req.body is
// not populated for multipart requests during the preValidation phase.

import CSRF from '@fastify/csrf'

const tokens = new CSRF()

/**
 * Verify a CSRF token against the secret stored in the request session.
 * @param {string|undefined} secret - req.session._csrf
 * @param {string|undefined} token  - the submitted _csrf value
 */
export function verifyCsrfToken(secret, token) {
  return Boolean(secret) && Boolean(token) && tokens.verify(secret, token)
}

/** Convenience wrapper for form-encoded requests where the token is in req.body. */
export function verifyCsrf(req) {
  return verifyCsrfToken(req.session && req.session._csrf, req.body && req.body._csrf)
}
